import { Category } from "@/components/trash_map";
export const BASE_URL = "http://192.168.0.137:8000";
export const BOTTOM_BAR_HEIGHT = 78;
export const CATEGORY_COLORS: Record<Category, string> = {
  recyclable: "#0ea5e9",
  compostable: "#22c55e",
  trash: "#6b7280",
  dropoff: "#ef4444",
};
export const WEEKLY_GOAL = 20;
export const NAME_TO_ABBR: Record<string, string> = {
  alabama: "AL",
  alaska: "AK",
  arizona: "AZ",
  arkansas: "AR",
  california: "CA",
  colorado: "CO",
  connecticut: "CT",
  delaware: "DE",
  florida: "FL",
  georgia: "GA",
  hawaii: "HI",
  idaho: "ID",
  illinois: "IL",
  indiana: "IN",
  iowa: "IA",
  kansas: "KS",
  kentucky: "KY",
  louisiana: "LA",
  maine: "ME",
  maryland: "MD",
  massachusetts: "MA",
  michigan: "MI",
  minnesota: "MN",
  mississippi: "MS",
  missouri: "MO",
  montana: "MT",
  nebraska: "NE",
  nevada: "NV",
  "new hampshire": "NH",
  "new jersey": "NJ",
  "new mexico": "NM",
  "new york": "NY",
  "north carolina": "NC",
  "north dakota": "ND",
  ohio: "OH",
  oklahoma: "OK",
  oregon: "OR",
  pennsylvania: "PA",
  "rhode island": "RI",
  "south carolina": "SC",
  "south dakota": "SD",
  tennessee: "TN",
  texas: "TX",
  utah: "UT",
  vermont: "VT",
  virginia: "VA",
  washington: "WA",
  "west virginia": "WV",
  wisconsin: "WI",
  wyoming: "WY",
};
export const FUN_FACTS: string[] = [
  "Flatten boxes to save bin space and improve sorting efficiency.",
  "Rinse and dry containers-cleaner loads are more likely to be recycled.",
  "Local rules vary a lot-always check your city's guidelines.",
  "Aluminum and glass can be recycled repeatedly without losing quality.",
  "Leaving caps on bottles helps some facilities capture them-follow local guidance.",
  "Clear labeling reduces contamination and improves recovery rates.",
  'Balancing "greens" and "browns" keeps your compost healthy and odor-free.',
  "Composting cuts methane emissions from landfills.",
  "Many cities now offer curbside organics collection-check availability.",
  "Wish-cycling (hoping an item is recyclable) increases contamination.",
  "Small loose items can jam sorting equipment-bag or bin them correctly.",
  "When uncertain, use a local lookup tool to avoid contaminating the bin.",
  "Batteries, electronics, and film plastics usually need special drop-off.",
  "Retail stores often host film-plastic collection bins.",
  "Check city sites for hazardous waste events and e-waste days.",
];
